@"
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/shop?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: shop
    password: shop
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  api-key: secret123
  products-base-url: http://products-service:8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
"@ | Set-Content .\backend\inventory-service\src\main\resources\application.yml
