server:
  port: 8080
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/shop?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: shop
    password: shop
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  api-key: secret123
  products-base-url: http://products-service:8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html

resilience4j:
  retry:
    instances:
      products:
        maxAttempts: 3
        waitDuration: 100ms
  circuitbreaker:
    instances:
      products:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
  timelimiter:
    instances:
      products:
        timeoutDuration: 2s
