server:
  port: 8080
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/shop?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: shop
    password: shop
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  api-key: secret123

springdoc:
  swagger-ui:
    path: /swagger-ui.html
